### ISSUE TITLE
Option to exclude a library

### ISSUE THREAD

**Issue by phairplay** [sup3rmark/PlexCheck#1]
Hi,
I have a downloaded movie folder which is linked to its own library on plex, it allows me to check the copy of a movie and then move it over to the main folder if it's okay.

Could you please add an option to exclude a library from any notifications?

**Comment by phairplay** [comment]
Hi,
Is there a possible ETA on the this?
(:

**Comment by sup3rmark** [comment]
I plan on working on it this week after work. Sorry, had a busy weekend!

**Comment by sup3rmark** [comment]
This functionality has been added. You can specify the Library ID of any libraries you want to omit in a comma-separated list.

Examples:
`.\PlexCheck.ps1 -ExcludeLib 4`
`.\PlexCheck.ps1 -ExcludeLib 1,2`
