### ISSUE TITLE
No information being returned for media

### ISSUE THREAD

**Issue by sup3rmark** [sup3rmark/PlexCheck#3]
All movies and TV shows are returning "no additional information" and no posters :(

**Comment by sup3rmark** [comment]
This is because we use OMDBAPI.com for metadata and posters, and they've recently started charging for API access ($5/mo if we want to get posters as well). Weighing my options here: pay the $60/year or come up with a workaround.

**Comment by twilliamsj** [comment]
OMDBAPI is offering free API keys again.    I was able to make a few additions and mods to the script to add the api key and i'm getting posters as well as information.
Also, i made a small change to the TVShows request.  

If the TV show has the same name as a movie (i.e. Lethal Weapon or S.W.A.T.) the tvshow will come back with the poster of the movie.

updates have been posted to https://github.com/twilliamsj/PlexProjects

**Comment by sup3rmark** [comment]
I've changed the source for media here to use https://www.themoviedb.org/ instead of OMDB. OMDB still charges for poster access, and TMDB doesn't. The recent update also improves matching media to IMDB by pulling the actual IMDB IDs from Plex or the TVDB.
